---
version: "3"
services:
  netbox:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    user: 'unit:root'
    volumes:
      - ./netbox_configuration.py:/opt/netbox/netbox/netbox/configuration.py:ro,Z
      - ./:/source:ro,Z
    tty: true

  postgres:
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - pgdata_netbox:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command:
      - sh
      - -c
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD
    env_file: ./.env

volumes:
  pgdata_netbox:
