name: Build and publish python package

on:
  release:
    types: [ published ]
  push:
    branches:
      - stefanhipfel-patch-1


jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1.2
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          PACKAGE_DIRECTORY: ./netbox_atlas_plugin
